# Generated by Django 4.2 on 2023-04-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_caisse'),
    ]

    operations = [
        migrations.AddField(
            model_name='caisse',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
