# Generated by Django 4.2 on 2023-04-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_caisse_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
