# Generated by Django 4.2 on 2023-04-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_caisse_caisse_jour'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caisse',
            old_name='return_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='caisse',
            name='test1',
        ),
        migrations.AlterField(
            model_name='caisse',
            name='caisse_jour',
            field=models.IntegerField(),
        ),
    ]
