# Generated by Django 4.2 on 2023-04-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_rename_return_date_caisse_date_remove_caisse_test1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caisse',
            name='caisse_jour',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
