# Generated by Django 3.2.12 on 2023-05-10 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20230510_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='input_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='sum_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
