# Generated by Django 4.2.1 on 2023-05-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='district',
            new_name='ville',
        ),
    ]
