# Generated by Django 4.2.1 on 2023-05-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_delete_mymodel_rename_district_order_ville'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='nom',
        ),
    ]
