# Generated by Django 4.2.1 on 2023-05-12 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_rename_name_order_nom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='Telphone',
        ),
    ]
