# Generated by Django 4.2.1 on 2023-05-12 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_rename_phone_order_telphone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='division',
            new_name='region',
        ),
    ]
