# Generated by Django 4.2.1 on 2023-05-12 15:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_rename_division_order_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dater',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
