# Generated by Django 4.2.1 on 2023-05-12 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0020_alter_order_options_alter_order_dater'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created', 'date_return')},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='dater',
            new_name='date_return',
        ),
    ]
