# Generated by Django 4.2.1 on 2023-05-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0021_alter_order_options_rename_dater_order_date_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='chekbook',
            field=models.BooleanField(default=False),
        ),
    ]
