# Generated by Django 4.2.1 on 2023-05-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_chekbook'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='account_no',
            new_name='N_compte',
        ),
    ]
