# Generated by Django 4.2.1 on 2023-05-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_chekbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('paypal', 'PayPal'), ('visa', 'Visa'), ('mastercard', 'MasterCard')], max_length=20),
        ),
    ]
